### ISSUE TITLE
repo desciption

### ISSUE THREAD

**Issue by ronboger** [neurodata/hack-neurodata#19]
change

MedHacks frontpage http://medhacks.org  — Edit

to

Hack@Neurodata frontpage http://hack.neurodata.io

i don't have rights to do this

**Comment by jovo** [comment]
i don't understand.
you want me to change the medhacks frontpage?
surely, you can do that?

On Tue, Oct 27, 2015 at 5:50 PM, ron boger notifications@github.com wrote:

> change
> 
> MedHacks frontpage http://medhacks.org — Edit
> 
> to
> 
> Hack@Neurodata frontpage http://hack.neurodata.io
> 
> i don't have rights to do this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/19.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by ronboger** [comment]
no, change the description on the git repo

On Tue, Oct 27, 2015 at 7:20 PM, joshua vogelstein <notifications@github.com
