### ISSUE TITLE
your schedule looks unprofessional

### ISSUE THREAD

**Issue by ronboger** [neurodata/hack-neurodata#2]
make it more professional

**Comment by jovo** [comment]
ok, take it out or fix it.
hackathon is over, so i no longer do things that other people can do ;)

On Mon, Oct 5, 2015 at 9:56 PM, ron boger notifications@github.com wrote:

> make it more professional
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/2.

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
gimme a date

**Comment by jovo** [comment]
11/22 is the main event, in glass pav, 9am - 9pm
11/23 - 11/25 is auxilliary, smaller, in clark on 3rd floor.
we should update the form to ask people which days they are coming.
thanks!

On Mon, Oct 26, 2015 at 7:26 PM, ron boger notifications@github.com wrote:

> gimme a date
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/2#issuecomment-151312911
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by ronboger** [comment]
will do
from is all you, you signed in with your Google account :)

**Comment by jovo** [comment]
done.
your turn :)

On Mon, Oct 26, 2015 at 8:43 PM, ron boger notifications@github.com wrote:

> will do
> from is all you, you signed in with your Google account :)
> On Oct 26, 2015 7:48 PM, "joshua vogelstein" notifications@github.com
> wrote:
> 
> > 11/22 is the main event, in glass pav, 9am - 9pm
> > 11/23 - 11/25 is auxilliary, smaller, in clark on 3rd floor.
> > we should update the form to ask people which days they are coming.
> > thanks!
> > 
> > On Mon, Oct 26, 2015 at 7:26 PM, ron boger notifications@github.com
> > wrote:
> > 
> > > gimme a date
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/hack-neurodata/issues/2#issuecomment-151312911
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/hack-neurodata/issues/2#issuecomment-151316147
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/2#issuecomment-151326967
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
Date selection is mutually exclusive.  e.g., I can't pick M-W if I choose
Sunday.

Best,
Will

On Mon, Oct 26, 2015 at 9:01 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
fixed
