### ISSUE TITLE
look at some data

### ISSUE THREAD

**Issue by jovo** [neurodata/hack-neurodata#3]
### core
- [x] in ocpviz; for an arbitrary token:
  - images are in view
  - can add layers
  - can change colors of layers
- [x] graph explorer
- [x] mr. ocp and load in gephi
- [ ] document which of the 3rd party client viewers work
### reach (make the rest of these work)
- [ ] ITK-SNAP; for an arbitrary CLARITY token
  -  see data
  -  overlay
- [ ] bigdataviewer (just look)
- [ ] vaa3d
- [ ] knossos
- [ ] viking
- [ ] reconstruct

**Comment by wrgr** [comment]
what do you have in mind here?  Any of the above as potential projects?  Or
all of the above...?

Worth prioritizing, perhaps - some exist, some need fixing (vaa3d,
bigdataviewer), and some we haven't really started.

Best,
Will

On Mon, Oct 26, 2015 at 6:42 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i've been told that they all work.
i want to know the answer.
if some don't work sometimes, that's fine, let's document

On Mon, Oct 26, 2015 at 6:45 PM, William Gray notifications@github.com
wrote:

> what do you have in mind here? Any of the above as potential projects? Or
> all of the above...?
> 
> Worth prioritizing, perhaps - some exist, some need fixing (vaa3d,
> bigdataviewer), and some we haven't really started.
> 
> Best,
> Will
> 
> On Mon, Oct 26, 2015 at 6:42 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > - Look at some data.
> > - in ocpviz; for an arbitrary token:
> > - images are in view
> > - can add layers
> > - can change colors of layers
> > - ITK-SNAP; for an arbitrary CLARITY token
> > - see data
> > - overlay
> > - bigdataviewer (just look)
> > - vaa3d
> > - knossos
> > - viking
> > - reconstruct
> > - graph explorer
> > - mr. ocp and load in gephi
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openconnectome/hack-neurodata/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/3#issuecomment-151306181
> .

## 

the glass is all full:  half water, half air.
neurodata.io
