### ISSUE TITLE
Manually annotate some data?

### ISSUE THREAD

**Issue by jovo** [neurodata/hack-neurodata#8]
### core
- [x] using one of the below options
### reach (the other 3)
- [ ] CATMAID
- [ ] knossos
- [ ] VAST
- [ ] Reconstruct
- [x] ITK-SNAP
- [ ] NeuTu

**Comment by wrgr** [comment]
https://github.com/janelia-flyem/NeuTu

Best,
Will

On Mon, Oct 26, 2015 at 6:59 PM, joshua vogelstein <notifications@github.com

**Comment by wrgr** [comment]
itk-snap is our baseline, right?  Think we just forgot.  That works today.

**Comment by jovo** [comment]
i've never tried, i don't know where the documentation is, etc.
so...maybe, a lot like everything else in that there are various claims of
things "working",
without much in the way of knowing/demoing/checking...

On Tue, Oct 27, 2015 at 1:58 PM, William Gray notifications@github.com
wrote:

> itk-snap is our baseline, right? Think we just forgot. That works today.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/hack-neurodata/issues/8#issuecomment-151587621
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
right - sorry to be unclear.  i was just observing that we should add
itk-snap to the list.
this is manno.  people have been using it at multiple sites.  Still work to
do to get documentation all linked up.

Best,
Will

On Tue, Oct 27, 2015 at 2:03 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
ok, added.
