### ISSUE TITLE
Share annotations (RAMONify)?

### ISSUE THREAD

**Issue by jovo** [neurodata/hack-neurodata#9]
### core
- [ ] somehow (eg, CAJAL)
### reach (seems like we should be able to pull this off at the event)
- [ ] upload annotation channel
- [ ] csv ingest script (with spec)

**Comment by wrgr** [comment]
I would advise this one.

Best,
Will

On Mon, Oct 26, 2015 at 6:59 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
see readme: i'm doing all of these without speaking to anybody on the team,
and then we'll fix together if they don't work until they do.
